import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faHospital,
  faUserMd,
  faStethoscope,
  faCalendarAlt,
  faUser,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faStar,
  faSignOutAlt,
  faHome,
  faSearch,
  faClock,
  faCalendarCheck,
  faFileAlt,
  faExclamationTriangle,
  faCheckCircle,
  faSpinner,
  faArrowLeft,
  faChevronRight,
  faChevronDown,
  faBell,
  faUserCircle,
  faCog,
  faSignInAlt,
  faEye,
  faEyeSlash,
  faLock,
  faPlus,
  faEdit,
  faTrash,
  faFilter,
  faCalendarPlus,
  faMapMarker,
  faMap,
  faLocationArrow,
  faHeartbeat,
  faAmbulance,
  faFirstAid,
  faBars,
  faTimes,
  faChevronUp,
  faAngleDown,
  faAngleUp,
  faAngleLeft,
  faAngleRight,
  faInfoCircle,
  faQuestionCircle
} from '@fortawesome/free-solid-svg-icons';

const icons = {
  hospital: faHospital,
  doctor: faUserMd,
  'user-md': faUserMd,
  stethoscope: faStethoscope,
  calendar: faCalendarAlt,
  'calendar-alt': faCalendarAlt,
  'calendar-check': faCalendarCheck,
  'calendar-plus': faCalendarPlus,
  user: faUser,
  'user-circle': faUserCircle,
  email: faEnvelope,
  envelope: faEnvelope,
  phone: faPhone,
  map: faMap,
  'map-marker': faMapMarker,
  'map-marker-alt': faMapMarkerAlt,
  'location-arrow': faLocationArrow,
  star: faStar,
  logout: faSignOutAlt,
  'sign-out-alt': faSignOutAlt,
  'sign-in-alt': faSignInAlt,
  home: faHome,
  search: faSearch,
  clock: faClock,
  'file-alt': faFileAlt,
  'notes-medical': faStethoscope, // fallback to stethoscope
  'exclamation-triangle': faExclamationTriangle,
  'check-circle': faCheckCircle,
  spinner: faSpinner,
  'arrow-left': faArrowLeft,
  'chevron-right': faChevronRight,
  'chevron-down': faChevronDown,
  'chevron-up': faChevronUp,
  bell: faBell,
  cog: faCog,
  eye: faEye,
  'eye-slash': faEyeSlash,
  lock: faLock,
  plus: faPlus,
  edit: faEdit,
  trash: faTrash,
  filter: faFilter,
  heartbeat: faHeartbeat,
  ambulance: faAmbulance,
  'first-aid': faFirstAid,
  'info-circle': faInfoCircle,
  'question-circle': faQuestionCircle,
  bars: faBars,
  times: faTimes,
  'angle-down': faAngleDown,
  'angle-up': faAngleUp,
  'angle-left': faAngleLeft,
  'angle-right': faAngleRight
};

export default function Icon({ name, className = '' }) {
  // Handle undefined or null name
  if (!name) {
    console.warn('Icon component received undefined name, using default icon');
    return <FontAwesomeIcon icon={faQuestionCircle} className={className} />;
  }
  
  const icon = icons[name] || icons['question-circle'] || faQuestionCircle;
  return <FontAwesomeIcon icon={icon} className={className} />;
}
